### ISSUE TITLE
Error in example.php

### ISSUE THREAD

**Issue by tchex** [ikkysleepy/adb#1]
Hello,
Not sure this is the right place to write this but I think there is an error in your example.php file:

$adb->setDevice(['host' => '192.168.10.113', 'port' => 5555]);

Should be:

$setDevice = $adb->setDevice(['host' => '192.168.10.113', 'port' => 5555]);

Thank you!

**Comment by ikkysleepy** [comment]
Thanks! I updated the example. :)
